### ISSUE TITLE
Feature: AutoPlay with TextToTalk Integration

### ISSUE THREAD

**Issue by Gasteno** [Kouzukii/ffxiv-betterautoplay#1]
Hi. Thanks for this great plugin. Not sure if the autoplay logic is using some sort of end of audio detection, but if it is, would love to see if this would be possible with unvoiced cutscenes in conjuntion with the TextToTalk plugin. Thanks again.

**Comment by Kouzukii** [comment]
Im not sure why you would need this plugin if you have TextToTalk

**Comment by Kouzukii** [comment]
If you are refering to "Game should automatically advance to the next voiceline once TextToTalk has finished playing its audio" that's a feature that should be implemented in TextToTalk, not this plugin

**Comment by Gasteno** [comment]
> If you are refering to "Game should automatically advance to the next voiceline once TextToTalk has finished playing its audio" that's a feature that should be implemented in TextToTalk, not this plugin

Ok thanks.
